// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaAngular.Infrastructure.Data;

namespace PruebaAngular.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PruebaAngularContext))]
    partial class AddNotificationSubscribers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Npgsql:ValueGenerationStrategy", Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PruebaAngular.Domain.AggregateModels.NotificationSubscriber", b =>
            {
                b.Property<Guid>("SubscriberId").HasColumnType("uuid").ValueGeneratedOnAdd();
                b.Property<string>("Email").HasColumnType("character varying(256)").HasMaxLength(256).IsRequired();
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.HasKey("SubscriberId");
                b.HasIndex("Email").IsUnique();
                b.ToTable("NotificationSubscribers");
            });
        }
    }
}
